DO $$
DECLARE
    serial_column record;
    sequence_name text;
    old_last_value bigint;
    old_is_called boolean;
BEGIN
    FOR serial_column IN SELECT * FROM (VALUES
        ('ibexa_user_invitation', 'id'),
        ('ibexa_user_invitation_assignment', 'id')
    ) AS c (table_name, column_name)
    LOOP
        -- A SERIAL column defaults to nextval('<sequence>'::regclass); an identity column has no default.
        SELECT substring(column_default FROM 'nextval\(''([^'']+)''::regclass\)') INTO sequence_name
        FROM information_schema.columns
        WHERE table_schema = current_schema()
            AND table_name = serial_column.table_name
            AND column_name = serial_column.column_name;
        CONTINUE WHEN sequence_name IS NULL;

        EXECUTE format('SELECT last_value, is_called FROM %s', sequence_name) INTO old_last_value, old_is_called;
        EXECUTE format('ALTER TABLE %I ALTER %I DROP DEFAULT', serial_column.table_name, serial_column.column_name);
        EXECUTE format('DROP SEQUENCE %s', sequence_name);
        EXECUTE format('ALTER TABLE %I ALTER %I ADD GENERATED BY DEFAULT AS IDENTITY', serial_column.table_name, serial_column.column_name);
        PERFORM setval(pg_get_serial_sequence(serial_column.table_name, serial_column.column_name), old_last_value, old_is_called);
    END LOOP;
END
$$;
