tables:
    ibexa_user_invitation:
        indexes:
            ibexa_user_invitation_email_idx:
                fields:
                    - email
            ibexa_user_invitation_hash_idx:
                fields:
                    - hash
        id:
            id:
                type: integer
                nullable: false
                options:
                    autoincrement: true
        fields:
            email:
                type: string
                nullable: false
                length: 255
            site_access_name:
                type: string
                nullable: false
                length: 255
            hash:
                type: string
                nullable: false
                length: 255
            creation_date:
                type: integer
                nullable: false
            used:
                type: boolean
                options:
                    default: false
        uniqueConstraints:
            ibexa_user_invitation_email_uindex:
                fields:
                    - email
                options:
                    lengths:
                        - 191
            ibexa_user_invitation_hash_uindex:
                fields:
                    - hash
                options:
                    lengths:
                        - 191

    ibexa_user_invitation_assignment:
        id:
            id:
                type: integer
                nullable: false
                options:
                    autoincrement: true
        fields:
            invitation_id:
                type: integer
                nullable: false
            user_group_id:
                type: integer
                nullable: true
            role_id:
                type: integer
                nullable: true
            limitation_type:
                type: string
                nullable: true
                length: 255
            limitation_value:
                type: string
                nullable: true
                length: 255
        foreignKeys:
            ibexa_user_invitation_assignment_ibexa_user_invitation_id_fk:
                foreignTable: ibexa_user_invitation
                fields:
                    - invitation_id
                foreignFields:
                    - id
                options:
                    onDelete: CASCADE
                    onUpdate: CASCADE
