services:

    Ibexa\Bundle\User\Controller\:
        resource: "../../Controller/*"
        exclude: "../../Controller/{Controller}"
        parent: Ibexa\Bundle\User\Controller\Controller

    Ibexa\Bundle\User\Controller\Controller:
        calls:
            - [setContainer, ["@service_container"]]
            - [performAccessCheck, []]
        tags: [controller.service_arguments]

    Ibexa\Bundle\User\Controller\PasswordResetController:
        autowire: true
        calls:
            - [setContainer, ['@service_container']]
        tags: [controller.service_arguments]

    Ibexa\Bundle\User\Controller\PasswordChangeController:
        autowire: true
        arguments:
            $siteAccessGroups: '%ezpublish.siteaccess.groups%'
        calls:
            - [setContainer, ['@service_container']]
            - [performAccessCheck, []]
        tags: [controller.service_arguments]

    Ibexa\Bundle\User\Controller\UserRegisterController:
        autowire: true
        arguments:
            $userActionDispatcher: '@ezplatform.content_forms.action_dispatcher.user'
        tags: [controller.service_arguments]

    Ibexa\Bundle\User\Controller\UserSettingsController:
        autowire: true
        calls:
            - [ setContainer, [ '@service_container' ] ]
        tags: [controller.service_arguments]
