services:
    Ibexa\User\EventListener\BuildSchemaSubscriber:
        autoconfigure: true
        public: false
        arguments:
            - '@=service("kernel").locateResource("@IbexaUserBundle/Resources/config/storage/schema.yaml")'

    Ibexa\Bundle\User\Migration\InstallSchemaMigration:
        autowire: true
        public: false
        arguments:
            $connection: '@ibexa.persistence.connection'
        tags:
            - { name: !php/const Ibexa\Contracts\DoctrineMigrations\Migrations\IbexaMigrationTag::TAG }

    Ibexa\Bundle\User\Migration\RenameSchemaTo5_0Migration:
        autowire: true
        public: false
        arguments:
            $connection: '@ibexa.persistence.connection'
        tags:
            - { name: !php/const Ibexa\Contracts\DoctrineMigrations\Migrations\IbexaMigrationTag::TAG }
