services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Ibexa\User\Strategy\DefaultThumbnailStrategy:
        arguments:
            $initialsFieldDefIdentifiers:
                - first_name
                - last_name
        tags:
            - { name: ibexa.repository.thumbnail.strategy.content, priority: -50 }
