services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Ibexa\User\UserSetting\:
        resource: "../../../lib/UserSetting/*"
        exclude: '../../../lib/UserSetting/Group/*'

    #
    # Main Service
    #
    Ibexa\User\UserSetting\UserSettingService: ~

    Ibexa\User\UserSetting\UserSettingArrayAccessor:

    #
    # User Settings Update Form Views
    #
    Ibexa\User\View\UserSettings\UpdateViewBuilder:
        arguments:
            $viewConfigurator: '@Ibexa\Core\MVC\Symfony\View\Configurator\ViewProvider'
            $viewParametersInjector: '@Ibexa\Core\MVC\Symfony\View\ParametersInjector\EventDispatcherInjector'
        tags:
            - { name: ibexa.view.builder }

    Ibexa\User\View\UserSettings\UpdateViewProvider:
        arguments:
            $matcherFactory: '@ibexa.user.view.user_setting.update.matcher_factory'
        tags:
            - { name: ibexa.view.provider, type: Ibexa\User\View\UserSettings\UpdateView, priority: 10 }

    ibexa.user.view.user_setting.update.default_configured:
        class: Ibexa\Bundle\Core\View\Provider\Configured
        arguments:
            $matcherFactory: '@ibexa.user.view.user_setting.update.default_matcher_factory'
        tags:
            - { name: ibexa.view.provider, type: Ibexa\User\View\UserSettings\UpdateView, priority: -1 }

    ibexa.user.view.user_setting.update.matcher_factory:
        class: Ibexa\Bundle\Core\Matcher\ServiceAwareMatcherFactory
        arguments:
            - '@Ibexa\Bundle\Core\Matcher\ViewMatcherRegistry'
            - '@ibexa.api.repository'
            - 'Ibexa\User\View\UserSettings\Matcher'

    ibexa.user.view.user_setting.update.matcher_factory.dynamically_configured:
        class: Ibexa\Core\MVC\Symfony\Matcher\DynamicallyConfiguredMatcherFactoryDecorator
        decorates: ibexa.user.view.user_setting.update.matcher_factory
        arguments:
            $innerConfigurableMatcherFactory: '@ibexa.user.view.user_setting.update.matcher_factory.dynamically_configured.inner'
            $configResolver: '@ibexa.config.resolver'
            $parameterName: user_settings_update_view

    ibexa.user.view.user_setting.update.default_matcher_factory:
        class: Ibexa\Bundle\Core\Matcher\ServiceAwareMatcherFactory
        arguments:
            - '@Ibexa\Bundle\Core\Matcher\ViewMatcherRegistry'
            - '@ibexa.api.repository'
            - 'Ibexa\User\View\UserSettings\Matcher'

    ibexa.user.view.user_setting.update.default_matcher_factory.dynamically_configured:
        class: Ibexa\Core\MVC\Symfony\Matcher\DynamicallyConfiguredMatcherFactoryDecorator
        decorates: ibexa.user.view.user_setting.update.default_matcher_factory
        arguments:
            $innerConfigurableMatcherFactory: '@ibexa.user.view.user_setting.update.default_matcher_factory.dynamically_configured.inner'
            $configResolver: '@ibexa.config.resolver'
            $parameterName: user_settings_update_view_defaults

    #
    # User Settings Implementations
    #
    Ibexa\User\UserSetting\Setting\Timezone:
        tags:
            - { name: ibexa.user.setting.value, identifier: timezone, group: location, priority: 50 }
            - { name: ibexa.user.setting.mapper.form, identifier: timezone }

    Ibexa\User\UserSetting\Setting\SubitemsLimit:
        tags:
            - { name: ibexa.user.setting.value, identifier: subitems_limit, group: browsing, priority: 20 }
            - { name: ibexa.user.setting.mapper.form, identifier: subitems_limit }

    Ibexa\User\UserSetting\Setting\CharacterCounter:
        tags:
            - { name: ibexa.user.setting.value, identifier: character_counter, group: content_edit, priority: 10 }
            - { name: ibexa.user.setting.mapper.form, identifier: character_counter }

    Ibexa\User\UserSetting\Setting\Language:
        arguments:
            $availableLocaleChoiceLoader: '@Ibexa\User\Form\ChoiceList\Loader\AvailableLocaleChoiceLoader'
        tags:
            - { name: ibexa.user.setting.value, identifier: language, group: location, priority: 10 }
            - { name: ibexa.user.setting.mapper.form, identifier: language }

    Ibexa\User\UserSetting\DateTimeFormat\FullDateTimeFormatterFactory: ~

    ibexa.user.settings.full_datetime_format.formatter:
        lazy: true
        factory: ['@Ibexa\User\UserSetting\DateTimeFormat\FullDateTimeFormatterFactory', 'getFormatter']
        class: 'Ibexa\User\UserSetting\DateTimeFormat\Formatter'

    Ibexa\User\UserSetting\Setting\FullDateTimeFormat:
        arguments:
            $formatter: '@ibexa.user.settings.full_datetime_format.formatter'
        tags:
            - { name: ibexa.user.setting.value, identifier: full_datetime_format, group: location, priority: 20 }
            - { name: ibexa.user.setting.mapper.form, identifier: full_datetime_format }

    Ibexa\User\UserSetting\DateTimeFormat\ShortDateTimeFormatterFactory: ~

    ibexa.user.settings.short_datetime_format.formatter:
        lazy: true
        factory: ['@Ibexa\User\UserSetting\DateTimeFormat\ShortDateTimeFormatterFactory', 'getFormatter']
        class: 'Ibexa\User\UserSetting\DateTimeFormat\Formatter'

    Ibexa\User\UserSetting\Setting\ShortDateTimeFormat:
        arguments:
            $formatter: '@ibexa.user.settings.short_datetime_format.formatter'
        tags:
            - { name: ibexa.user.setting.value, identifier: short_datetime_format, group: location, priority: 30 }
            - { name: ibexa.user.setting.mapper.form, identifier: short_datetime_format }

    Ibexa\User\UserSetting\DateTimeFormat\FullDateFormatterFactory: ~

    ibexa.user.settings.full_date_format.formatter:
        lazy: true
        factory: ['@Ibexa\User\UserSetting\DateTimeFormat\FullDateFormatterFactory', 'getFormatter']
        class: 'Ibexa\User\UserSetting\DateTimeFormat\Formatter'

    Ibexa\User\UserSetting\DateTimeFormat\FullTimeFormatterFactory: ~

    ibexa.user.settings.full_time_format.formatter:
        lazy: true
        factory: ['@Ibexa\User\UserSetting\DateTimeFormat\FullTimeFormatterFactory', 'getFormatter']
        class: 'Ibexa\User\UserSetting\DateTimeFormat\Formatter'

    Ibexa\User\UserSetting\DateTimeFormat\ShortDateFormatterFactory: ~

    ibexa.user.settings.short_date_format.formatter:
        lazy: true
        factory: ['@Ibexa\User\UserSetting\DateTimeFormat\ShortDateFormatterFactory', 'getFormatter']
        class: 'Ibexa\User\UserSetting\DateTimeFormat\Formatter'

    Ibexa\User\UserSetting\DateTimeFormat\ShortTimeFormatterFactory: ~

    ibexa.user.settings.short_time_format.formatter:
        lazy: true
        factory: ['@Ibexa\User\UserSetting\DateTimeFormat\ShortDateFormatterFactory', 'getFormatter']
        class: 'Ibexa\User\UserSetting\DateTimeFormat\Formatter'

    Ibexa\User\UserSetting\Group\LocationGroup:
        tags:
            - { name: ibexa.user.setting.group, identifier: location, priority: 30 }

    Ibexa\User\UserSetting\Group\EditContentGroup:
        tags:
            - { name: ibexa.user.setting.group, identifier: content_edit, priority: 20 }

    Ibexa\User\UserSetting\Group\BrowsingGroup:
        tags:
            - { name: ibexa.user.setting.group, identifier: browsing, priority: 10 }

    Ibexa\User\UserSetting\Group\CustomGroup:
        tags:
            - { name: ibexa.user.setting.group, identifier: custom, priority: 0 }

